### PR TITLE
Utilize modern build status

### PR DESCRIPTION
**Pull request by NotMyFault**
The change proposed utilizes the modern build icons, like they are used in other parts of Jenkins.
The pom change bumps the baseline to the LTS version the change has been introduced in.

Before:

My proposed change:

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by NotMyFault** [comment]
Mind taking a look @car-roll ?

**Review by car-roll — APPROVED** [review]

**Comment by NotMyFault** [comment]
It looks like something went wrong that prevents CD to perform a release. The merge commit is stuck on building.

**Comment by car-roll** [comment]
I'm merging in another PR that is ready, so let's see if that clears it up

**Comment by NotMyFault** [comment]
> I'm merging in another PR that is ready, so let's see if that clears it up

That seems to have resolved it, thanks!

**Pull request merged**
