### PR TITLE
Revert removal of TagsAction: Provide Binding for Attaching Metadata To Stages/Steps

### PR DESCRIPTION
**Pull request by svanoort**
This reverts commit 428319414b7fa7288bec1652202188a1ea52daa5.

The original code was approved in https://github.com/jenkinsci/workflow-api-plugin/pull/12 but reverted when the downstream consumer was killed (to be restored at a later date when the next consumer came around). 

Now a consumer has arisen anew!

### CODE REVIEW

**Comment by svanoort** [comment]
@abayer all for you mang

**Comment by jglick** [comment]
Pending a downstream PR.

**Comment by abayer** [comment]
I'll have the new Declarative PR for synthetic stages up today, and then we'll be waiting on @vivek and others at Blue Ocean to consume *that* PR.

**Comment by abayer** [comment]
:bee: and downstream PR created. =)

**Comment by jglick** [comment]
https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/47 still appears to be under active discussion, and there is no apparent `blueocean` PR yet, so I think this is still in a pending state.

**Comment by jglick** [comment]
What issue are you purporting to solve with this plus https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/47 plus https://github.com/jenkinsci/blueocean-plugin/pull/608? It does seem to have much of anything to do with the reported purpose of JENKINS-26522. Can you update the PR title and description to describe what the intent is?

**Comment by svanoort** [comment]
@jglick This was already approved, the only blocker was the need for the consumer of this API to exist, which we now have.  I have to admit I'm bit confused -- why the change of heart here?

**Comment by abayer** [comment]
re-:bee:, fwiw.

**Comment by vivek** [comment]
🐝 there is blueocean PR that has use case to validate these APIs. LGTM.

**Comment by i386** [comment]
I assume this is https://issues.jenkins-ci.org/browse/JENKINS-26522 ? Should be in review?

**Comment by svanoort** [comment]
*Part* of Jenkins-26522.  There's a couple more pieces needed to get the complete result.

**Pull request merged**
