### PR TITLE
[JENKINS-71970] Potentially solve memory leak

### PR DESCRIPTION
**Pull request by rsandell**
### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by jglick** [comment]
https://issues.jenkins.io/browse/JENKINS-71970 FTR

**Comment by jglick** [comment]
amending #294

**Review by jglick — APPROVED** [review]

**Comment by alexsch01** [comment]
Did this fix the memory leak for anyone?

**Comment by rsandell** [comment]
I haven't received any feedback yet.

**Comment by alexsch01** [comment]
@rsandell the memory leak doesn't seem to be resolved

**Comment by alexsch01** [comment]
mattik: ```We're also still seeing the same problem after updating to 1275.veb_e0969ddf9e.```

**Pull request merged**
