### PR TITLE
Reduce usages of Guava

### PR DESCRIPTION
**Pull request by basil**
Reduces some usages of Guava without affecting serialized state or backward compatibility.

### CODE REVIEW

**Comment by jglick** [comment]
Relation to #159?

**Comment by basil** [comment]
> Relation to #159?

This is ready to merge as-is and #159 isn't?

**Comment by olamy** [comment]
#159 is more agressive  :)

**Comment by jglick** [comment]
So merge this now, and mark #159 as draft until it can be finished.

**Comment by basil** [comment]
> So merge this now, and mark #159 as draft until it can be finished.

Agreed. @olamy are you interested in merging this?

**Pull request merged**
