### PR TITLE
Handle also RuntimeException from save()

### PR DESCRIPTION
**Pull request by jglick**
https://ci.jenkins.io/job/Plugins/job/workflow-durable-task-step-plugin/job/PR-53/5/console showed some flakes:

```
java.lang.RuntimeException: Failed to serialize org.jenkinsci.plugins.workflow.support.storage.SimpleXStreamFlowNodeStorage$Tag#actions for class org.jenkinsci.plugins.workflow.support.storage.SimpleXStreamFlowNodeStorage$Tag
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:256)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1026)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1015)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:988)
	at hudson.XmlFile.write(XmlFile.java:171)
	at org.jenkinsci.plugins.workflow.support.storage.SimpleXStreamFlowNodeStorage.saveActions(SimpleXStreamFlowNodeStorage.java:111)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.saveActions(CpsFlowExecution.java:887)
	at org.jenkinsci.plugins.workflow.graph.FlowNode.save(FlowNode.java:462)
	at org.jenkinsci.plugins.workflow.graph.FlowNode.persistSafe(FlowNode.java:468)
	at org.jenkinsci.plugins.workflow.graph.FlowNode.access$100(FlowNode.java:77)
	at org.jenkinsci.plugins.workflow.graph.FlowNode$1.add(FlowNode.java:427)
	at org.jenkinsci.plugins.workflow.graph.FlowNode$1.add(FlowNode.java:417)
	at java.util.AbstractList.add(AbstractList.java:108)
	at hudson.model.Actionable.addAction(Actionable.java:152)
	at org.jenkinsci.plugins.workflow.support.steps.ExecutorStepExecution$PlaceholderTask$PlaceholderExecutable.run(ExecutorStepExecution.java:657)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)
Caused by: java.lang.RuntimeException: Failed to serialize org.jenkinsci.plugins.workflow.support.actions.WorkspaceActionImpl#path for class org.jenkinsci.plugins.workflow.support.actions.WorkspaceActionImpl
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:256)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:64)
	at com.thoughtworks.xstream.converters.collections.ArrayConverter.marshal(ArrayConverter.java:45)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
	... 25 more
Caused by: com.thoughtworks.xstream.io.StreamException:  : null
	at com.thoughtworks.xstream.core.util.QuickWriter.flush(QuickWriter.java:77)
	at com.thoughtworks.xstream.core.util.QuickWriter.write(QuickWriter.java:49)
	at com.thoughtworks.xstream.io.xml.PrettyPrintWriter.writeText(PrettyPrintWriter.java:279)
	at com.thoughtworks.xstream.io.xml.PrettyPrintWriter.writeText(PrettyPrintWriter.java:231)
	at com.thoughtworks.xstream.io.xml.PrettyPrintWriter.setValue(PrettyPrintWriter.java:214)
	at com.thoughtworks.xstream.io.WriterWrapper.setValue(WriterWrapper.java:45)
	at com.thoughtworks.xstream.converters.SingleValueConverterWrapper.marshal(SingleValueConverterWrapper.java:45)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:51)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
	... 40 more
Caused by: java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:216)
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78)
	at java.nio.channels.Channels.writeFully(Channels.java:101)
	at java.nio.channels.Channels.access$000(Channels.java:61)
	at java.nio.channels.Channels$1.write(Channels.java:174)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at java.io.BufferedWriter.flush(BufferedWriter.java:254)
	at hudson.util.AtomicFileWriter.flush(AtomicFileWriter.java:97)
	at com.thoughtworks.xstream.core.util.QuickWriter.flush(QuickWriter.java:75)
	... 51 more
```

While I am not really sure why `AtomicFileWriter.flush` would be failing like this, it is not expected that

```java
flowNode.addAction(new WorkspaceActionImpl(workspace, flowNode));
```

would fail with a `RuntimeException` and thus abort the `node` step.

@reviewbybees

### CODE REVIEW

**Comment by svanoort** [comment]
Please find out *why* it's throwing that -- it looks like the write operation itself is being interrupted.

**Comment by jglick** [comment]
I am not “swallowing” the exception—it is still getting logged. The damage is simply better contained than it was before. As to the root cause, I really have no idea, and since the test in question passes for me locally, it would be a lot of work to figure it out. Right now I do not have time for that. Feel free to do some investigation on your own later; in the meantime, this patch should be helpful in limiting the scope of a problem.

**Comment by jglick** [comment]
You are making the perfect be the enemy of the good I guess. What concretely do you propose?

**Comment by svanoort** [comment]
@jglick Concretely I'd like to see the root cause identified and resolved.   It looks like something is actually interrupting the serialization operation and that makes me go "huh?"Something needs to be waiting for that write to complete rather than interrupting it, and that's where the bug lies.  

A general IOException makes sense to catch because that's fairly common failure mode, but this particular behavior doesn't make sense to catch and log.

Unless it's part of an effort to harden the general system against RuntimeExceptions and Errors, which would be nice.

**Comment by jglick** [comment]
I just have no solid hypothesis at the moment for what could be interrupting the thread, and unfortunately the JVM does not record the stack trace of the _other_ thread calling `Thread.interrupt`. This is a nightmare for big systems like Jenkins.

I suppose this could be considered

> part of an effort to harden the general system against RuntimeExceptions and Errors

I would put it this way: if the code had always been catching `Exception`, and then someone obsessing over Checkstyle violations complained that “you should not be catching `Exception` when a specific set of typed exceptions is declared!” and proposed a PR to change it to catch `IOException`, I would likely reject the PR on the grounds that they could not possibly be improving anything and might be making something worse.

At any rate, I do not know whether this kind of error could happen in production. Perhaps it is only an artifact of the test environment, such as a test timeout being exceeded (for some _unrelated_ reason), the test being interrupted, then the interruption causing this error to be thrown up and be treated as the primary failure.

**Comment by svanoort** [comment]
My hope is to gain some insight into the root cause of this and a couple other lingering nasties in the process of ongoing testing for the [JENKINS-47170](https://issues.jenkins-ci.org/browse/JENKINS-47170) epic since I've got to expand test coverage for some odd circumstances.

**Comment by jglick** [comment]
Saw this again today as flakes of `ExecutorStepTest.buildShellScriptOnSlaveWithDifferentResumePoint`. Maybe best to just `@Ignore` this test as I do not think it corresponds to a real situation; an actual `/safeRestart` should be waiting for work in the CPS VM thread to complete.

**Comment by jglick** [comment]
https://github.com/jenkinsci/jenkins/pull/3167 would also have helped.

**Comment by jglick** [comment]
Did what I could to both investigate and look for complementary solutions. This patch is still a net gain IMO: `Actionable.addAction` declares no exceptions, so we should not be throwing any.

**Comment by jglick** [comment]
I still suspect the root problem was an unrealistic behavior of `RestartableJenkinsRule`, but as you say, stronger test infrastructure in JENKINS-47170 would turn up any real problems regardless.

**Comment by svanoort** [comment]
@jglick There's some hardening embedded in the JENKINS-47170 that will catch some of the persistence issues and more gracefully handle exceptions -- I consider this PR "on hold" until we can see if that one provides the coverage we need.  

Is it as simple as running `ExecutorStepTest.buildShellScriptOnSlaveWithDifferentResumePoint` a variety of times?

**Comment by jglick** [comment]
> Is reproducing this as simple as running `ExecutorStepTest.buildShellScriptOnSlaveWithDifferentResumePoint` a variety of times?

Unknown.

**Comment by jglick** [comment]
ping

**Comment by jglick** [comment]
@svanoort unfortunately I am not sure about reproducibility—I just saw some test flakes and decided to make what seemed like a simple and safe robustness improvement. Obviously it would be nice to _additionally_ track down and solve the root cause of the error.

**Pull request merged**
