### PR TITLE
[JENKINS-65398] Terminology updates for public strings. 

### PR DESCRIPTION
**Pull request by kerogers-cloudbees**
[JENKINS-65398] Terminology updates

CloudBees is updating terminology to remove offensive text. During this ongoing initiative, “controller” replaces “master,” “agent” replaces “slave,” “allowlist” replaces “whitelist,” and “denylist” replaces “blacklist.”

This update does not change any code or variable naming.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by kerogers-cloudbees** [comment]
Jenkins jira epic https://issues.jenkins.io/browse/JENKINS-65398

**Review by amuniz — APPROVED** [review]

**Review by olamy — APPROVED** [review]

**Comment by kerogers-cloudbees** [comment]
@olamy Can we have a release of this plugin made that includes these changes? Thanks!

**Comment by olamy** [comment]
@kerogers-cloudbees happy to do it but just figure out I can't deploy. Need to wait this first https://github.com/jenkins-infra/repository-permissions-updater/pull/1979

**Comment by Vlatombe** [comment]
@olamy I just checked the linked pr and you should have access now.

**Comment by olamy** [comment]
2.44 has been released

**Pull request merged**
