### PR TITLE
Use readResolve to deduplicate FlowNode IDs

### PR DESCRIPTION
**Pull request by svanoort**
Should reduce memory footprint for Jenkins pipeline a bit and simplify garbage collection some. 

See [JENKINS-39456](https://issues.jenkins-ci.org/browse/JENKINS-39456)

Replaces https://github.com/jenkinsci/workflow-support-plugin/pull/24

### CODE REVIEW

**Comment by svanoort** [comment]
WIP until tested for deduplication manually

**Comment by svanoort** [comment]
Now upstream of https://github.com/jenkinsci/workflow-cps-plugin/pull/82

**Comment by svanoort** [comment]
Tested manually and this looks fine too.

**Comment by svanoort** [comment]
@reviewbybees especially @jglick

**Comment by abayer** [comment]
Sure, I guess? =) :bee:

**Pull request merged**
